---
name: Renato Valladares Panaro
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: Statistics, BSc
position: Statistician
address: Belo Horizonte, MG
phone: +55 21 9 97188 7955
email: renatovp@ufmg.br
website: rvpanaro.github.io
github: rvpanaro
linkedin: rvpanaro
twitter: 
headcolor: 414141
output: vitae::awesomecv
header_includes:
  - \usepackage{cite}
  - \ExecuteBibliographyOptions{useprefix=true}
  - renewcommand{\bibfont}{\normalfont\fontsize{10}{12.4}\sffamily}
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
library(RefManageR)
knitr::opts_chunk$set(echo = FALSE)
options(tinytex.verbose = TRUE)
```

# Education
```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "MS c in Statistics", "Federal University of Minas Gerais", "Minas Gerais, Brazil", "Mar. 2018 - Fev. 2020", "Outstanding performance (> 90) for: Statistical Inference (DIP EST825U), Stat. Methods of Reliability and Survival Analysis (DIP EST863U), Computational Methods Applied to Statistics (DIP EST865U) and Mathematical analysis (DIP EST865B)",
    "MS c in Statistics", "Federal University of Minas Gerais", "Minas Gerais, Brazil", "Mar. 2018 - Fev. 2020", "Contributing with an open source R package to allow Semiparametric Survival Analysis using Bernstein Polynomial in R",
    "BS c in Statistics", "Federal Fluminense University", "Rio de Janeiro, Brazil", "Apr. 2013 - Dez. 2017", "WAM of 76",
    "BS c in Statistics", "Federal Fluminense University", "Rio de Janeiro, Brazil", "Apr. 2013 - Dez. 2017", "Term paper: Modeling and Forecasting Effective Annual Inflation Measured by IPCA.",
    "BS c in Statistics", "Federal Fluminense University", "Rio de Janeiro, Brazil", "Apr. 2013 - Dez. 2017", "Outstanding performance for: Sources of Information (GET00134), Data Visualization (GET00183), Applied Statistics (GET00128), Scientific Research Methodology (GET00137), Multivariate Analysis (GET00126) and Time Series Analysis (GET00127)",
        "Brazil Scientific Mobility Program", "University of Wisconsin Platteville", "Wisconsin, United States", "Jun. 2014 - May 2015", "GPA: 3.413",
      "Brazil Scientific Mobility Program", "University of Wisconsin Platteville", "Wisconsin, United States", "Jun. 2014 - May 2015", "Outstanding performance for: 
  Global Business (BUSADMIN 1300), Management Accounting (ACCTING 2020), Data Analysis & Decision Mkg (BUSADMIN 2340) and Principles of Macroeconomics (ECONOMIC 2130)",
        "Brazil Scientific Mobility Program", "University of Wisconsin Platteville", "Wisconsin, United States", "Jun. 2014 - May 2015", "Attended Summer ESL classes with outsdanding performance for: US Culture (ESL 134), Acad Listening and Note-Taking (ESL 151), Acad Speaking (ESL 152) and Special Topics (ESL 155)",
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Experience
```{r}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Research Assistant (Fundação Christiano Ottoni)", "Decision Support and Reliability Lab, LADEC", "School of Engineering-UFMG", "Oct. 2018 - Present", "Supervisors include Marcelo Azevedo Costa and Vinícius Diniz Mayrink", 
    "Research Assistant (Fundação Christiano Ottoni)", "Decision Support and Reliability Lab, LADEC", "School of Engineering-UFMG", "Oct. 2018 - Present", "Consulting project with Companhia Energética de Minas Gerais, CEMIG", 
     "Research Assistant (Fundação Christiano Ottoni)", "Decision Support and Reliability Lab, LADEC", "School of Engineering-UFMG", "Oct. 2018 - Present", "Contributing to the development of an open source package to ease Bayesian Structured Equation Modelling via RStan and Shiny",
   "Research Assistant (Fundação Christiano Ottoni)", "Decision Support and Reliability Lab, LADEC", "School of Engineering-UFMG", "Oct. 2018 - Present", "The project consisted of Computational statistical modeling of the CEMIG-D business model using databases and technical knowledge (P&D D636)",
      "Research Intern (Fundação Euclides da Cunha)", "Documentation Active & Intelligent Design Laboratory, ADDLABS", "IC-UFF", "Oct. 2017 - Dez. 2017", "Supervisors include Rodrigo Salvador Monteiro and Ludmilla da Silva Viana Jacobson",
      "Research Intern (Fundação Euclides da Cunha)", "Documentation Active & Intelligent Design Laboratory, ADDLABS", "IC-UFF", "Oct. 2017 - Dez. 2017", "Consulting project with Shell Brasil",
    "Research Intern (Fundação Euclides da Cunha)", "Documentation Active & Intelligent Design Laboratory, ADDLABS", "IC-UFF", "Oct. 2017 - Dez. 2017", "Contributed with consistency checks, data granularity reduction and time series visualizations of structured in large datasets (17 million).",
      "Research Intern (Fundação Euclides da Cunha)", "Documentation Active & Intelligent Design Laboratory, ADDLABS", "IC-UFF", "Oct. 2017 - Dez. 2017", "The ADDSSI project aimed to research the use of artificial intelligence techniques to support the diagnosis of flow and pressure control anomalies in a water injection system of a UEP. In addition, it offers a dynamic model of the injection system of an FPSO and allows simulations of the behavior of its equipment and its control loop, comparing the results with the actual measurements loaded directly from the process plant. (ADDSSI)",
    "Intern", "Planejamento e Pesquisa Ltda, GPP", "Niterói, Rio de Janeiro", "Jan. 2016 - Mar. 2018", "Supervisors include Adriano Von Pfuhl Rodrigues and Francisco Guimarães",
      "Intern", "Planejamento e Pesquisa Ltda, GPP", "Niterói, Rio de Janeiro", "Jan. 2016 - Mar. 2018", "Consulting with Naturgy Energy Group S.A., ILOS, CASSI, Previ and local politicians",
  "Intern", "Planejamento e Pesquisa Ltda, GPP", "Niterói, Rio de Janeiro", "Jan. 2016 - Mar. 2018", "Analytics support to electoral and market research, outcome reporting and data consistency supervision",
  "Volunteer", "Feira Brasileira de Colégios de Aplicação e Escolas Técnicas, VII FEBRAT", "Pedagogical Center-UFMG, ", "October 23, 2019", "Evaluation of the scientific merit of the papers submitted to the event.",
    "Volunteer", "Feira Brasileira de Colégios de Aplicação e Escolas Técnicas, VII FEBRAT", "Pedagogical Center-UFMG, ", "October 23, 2019", "VII FEBRAT is a scientific fair that promotes the dissemination of works developed by students of Basic Education and Vocational and Technological Education under the guidance of teachers from different areas of knowledge. The theme of the 2019 edition is “Bioeconomics: Diversity and Wealth for Sustainable Development”.",
) %>% 
  detailed_entries(role, dates, company, loc, details)
```

\newpage

# Achievements
## Certificates and licenses
```{r}
tribble(
  ~ certificate, ~ from, ~ year,
  "TOEFL iBT (score 96)", "ETS Global", "2019",
  "Accredited Statistician", "CONRE-2", "2018",
  "Hands on Deep Learning course extension", "DCC-UFMG", "2018",
  "Rn00bs founder", "Rn00bs", "2018"
) %>%
  brief_entries(certificate, year, from)
```

## Scholarships
```{r}
tribble(
  ~ scholarship, ~ from, ~ year,
  "International experience through one year scholarship granted by Higher Education Improvement Coordination (CAPES) at UWP.", "UWP", "2014",
) %>%
  brief_entries(scholarship, year, from)
```

# Technical Skills
```{r}
tribble(
  ~ skill, ~ category,
  "Analytical", "Statistical Modelling, Bayesian Statistics, Survival Analysis and Structural Equation Modelling",
  "Programming", "R (advanced), LaTeX (advanced), Stan (advanced), HTML, TOML, CSS, JavaScript, SQL, Python, SAS and MQL",
  "Python libraries", "Pandas, numpy, Matplotlib and Seaborn, Scikit-learn",
  "Tools", "Git, RStudio, Jupyter, SAS 9.0, MySQL Workbench and MetaTrader 5"
) %>%
  detailed_entries(with = skill, what = category)
```

# Presentations
```{r}
tribble(
  ~ competition, ~ from, ~ year,
  "Semiparametric Survival Analysis via Bernstein Polynomials", "SER IV", "2019",
  "Predictive modeling of economic and financial monitoring of The Brazilian Electricity Regulatory Agency (ANEEL)", "CSDS", "2019",
  "Bernstein Polynomial based Proportional Hazards regression", "WASA", "2019"

) %>%
  brief_entries(competition, year, from)
```

# Papers
```{r}
bibliography_entries(file = "ref.bib")
```
